export enum ColorsEnum {
  BASE_GRAY = "#E5E9F2",
  WHITE = "#FFFFFF",
  INTELLIGENCE = "#00A6FF",
  CUNNING = "#77D353",
  CELERITY = "#FFC82C",
  TENACITY = "#F95F62",
  BASIC_ATTACK = "#A54BFF",
}
